# Generated by Django 5.0.3 on 2024-03-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.CharField(max_length=5),
        ),
    ]
