# Generated by Django 5.0.3 on 2024-03-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeApp', '0002_alter_recipe_prep_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(max_length=100, verbose_name='Recipe cuisine'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='diet',
            field=models.CharField(max_length=100, null=True, verbose_name='Recipe diet'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='keywords',
            field=models.CharField(max_length=300, verbose_name='Recipe keyword'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='link',
            field=models.CharField(max_length=200, verbose_name='Recipe link'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Recipe name'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.CharField(max_length=5, verbose_name='Recipe time'),
        ),
    ]
